[package]
name = "deadpool-surrealdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool = "0.9.5"
deadpool-sync = "0.1.0"
surrealdb = "1.0.0-beta.9"
